### ISSUE TITLE
Send and receive ECUMotorCommands struct

### ISSUE THREAD

**Issue by edward-noe** [solarcaratuva/Rivanna2#72]
- [x] #86
- [x] #87
- [x] #88

**Comment by Goutham888** [comment]
We printed integer values to check. 
We found a minimum of 8290 and a max of 40505. We also checked the board with the multimeter and got min 0.41V and max 2.04V.

Since for both measurements the minimum is 20% of the maximum we have some confidence that the values are correct. We think the unpressed mode of the throttle might just be outputting a non-zero value. We think mapping the throttle to a curve or piecewise function would prevent small changes in pressure resulting in not-totally-predictable power outputs.

**Comment by edward-noe** [comment]
We need to:
- [ ] Send `ECUMotorCommands` structs from the ECU board
- [ ] Change `MotorInterface` to support our new digital POT
- [ ] Extend `MotorCANInterface` to handle `ECUMotorCommands` structs
